[project]
name = "arkiv-sdk"
version = "1.0.0a4"
description = "Python SDK for Arkiv networks - Web3.py + Entities"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "Arkiv Network", email = "matthias.zimmermann@golem.network"}
]
keywords = ["arkiv", "web3", "blockchain", "ethereum", "storage", "entities", "l2", "layer2"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Distributed Computing",
]
dependencies = [
    "web3>=7.13.0,<7.14.0",
]

[project.urls]
Homepage = "https://github.com/Arkiv-Network/arkiv-sdk-python"
Documentation = "https://github.com/Arkiv-Network/arkiv-sdk-python#readme"
Repository = "https://github.com/Arkiv-Network/arkiv-sdk-python"
Issues = "https://github.com/Arkiv-Network/arkiv-sdk-python/issues"
Changelog = "https://github.com/Arkiv-Network/arkiv-sdk-python/blob/main/CHANGELOG.md"

[project.optional-dependencies]
# Optional: Local development node support (ArkivNode)
dev = [
    "testcontainers>=4.13.1",
    "websockets>=13.0",
]

[dependency-groups]
test = [
    "pytest>=8.4.2",
    "pytest-asyncio>=0.24.0",
    "pytest-cov>=7.0.0",
    "pytest-xdist>=3.8.0",
    "testcontainers>=4.13.1",
    "websockets>=13.0",
    "python-dotenv>=1.0.0",
]
lint = [
    "mypy>=1.13.0",
    "ruff==0.13.2",
    "pre-commit>=4.0.0",
]
dev = [
    "ipython>=8.37.0",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
filterwarnings = [
    "ignore:The @wait_container_is_ready decorator is deprecated.*:DeprecationWarning:testcontainers.*",
    "ignore:websockets.legacy is deprecated;.*",
]

[tool.mypy]
# Strict type checking configuration
strict = true
warn_return_any = true
warn_unused_configs = true
no_implicit_reexport = true
show_error_codes = true
show_column_numbers = true

# Per-module options
[[tool.mypy.overrides]]
module = [
    "testcontainers.*",
    "websockets.*",
]
ignore_missing_imports = true

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "W", "F", "I", "B", "C4", "UP", "RUF"]
ignore = [
    "E501",    # Line too long (handled by formatter)
    "UP046",   # Generic class uses Generic subclass (need Python 3.10 compatibility)
]

[tool.ruff.format]
quote-style = "double"
